from . import models
from . import stock_inventory
from . import stock_picking
from . import res_partner
from . import fal_cust_vendor_group
from . import fal_reason_code
from . import fal_no_rangka
from . import fal_product_dimension
from . import product